added logs for when miner state changes
filecoin-project/specs-actors pull request #1518
Opened 2021-10-20 00:01 UTC by laudiacay

This PR adds logs for when miner state balances change as requested in #1500. There were some spots where i wasn’t sure if the functions in miner_state.go were returning the right value, so i flagged those, and also found one spot where the wrong thing was being logged and fixed it.

This PR came from my IPad so sorry in advance if there’s anything wonky... tried to check diffs over carefully

2021-11-19 21:13 UTC, arajasek requested changes
Some remarks:

- i don't think periods in logs is standard go practice...suggested changing those to commas
- would consider dropping most of these logs to DEBUG, but defer to @jennijuju 
- `about` and `amount` are different words, iPad lady

2021-11-19 21:13 UTC, arajasek commented on actors/builtin/miner/miner_actor.go
> +			rt.Log(rtt.INFO, "subtracted burnt deposits from precommit deposit while cleaning up expired precommits. amount burnt: %v, new total: %v", depositToBurn, st.PreCommitDeposits)
```suggestion
			rt.Log(rtt.INFO, "subtracted burnt deposits from precommit deposit while cleaning up expired precommits. amount burnt: %v, new total: %v", depositToBurn, st.PreCommitDeposits)
```
```suggestion
			rt.Log(rtt.INFO, "subtracted burnt deposits from precommit deposit while cleaning up expired precommits, amount burnt: %v, new total: %v", depositToBurn, st.PreCommitDeposits)
```

2021-11-19 21:13 UTC, arajasek commented on actors/builtin/miner/miner_actor.go
> +		rt.Log(rtt.INFO, "paid fee debt. amount from vesting table: %v, amount from balance: %v, new fee debt: %v", penaltyFromVesting, penaltyFromBalance, st.FeeDebt)
```suggestion
		rt.Log(rtt.INFO, "paid fee debt, amount from vesting table: %v, amount from balance: %v, new fee debt: %v", penaltyFromVesting, penaltyFromBalance, st.FeeDebt)
```

2021-11-19 21:13 UTC, arajasek commented on actors/builtin/miner/miner_actor.go
> +		rt.Log(rtt.INFO, "added initial pledge. amt added: %v, new total: %v", totalInitialPledge.Neg(), st.InitialPledge)
```suggestion
		rt.Log(rtt.INFO, "added initial pledge, amt added: %v, new total: %v", totalInitialPledge.Neg(), st.InitialPledge)
```

2021-11-19 21:13 UTC, arajasek commented on actors/builtin/miner/miner_actor.go
> +		rt.Log(rtt.INFO, "added penalty to fee debt. about added: %v, new total fee debt: %v", penalty, st.FeeDebt)
```suggestion
		rt.Log(rtt.INFO, "added penalty to fee debt, amount added: %v, new total fee debt: %v", penalty, st.FeeDebt)
```

2021-11-19 21:13 UTC, arajasek commented on actors/builtin/miner/miner_actor.go
> +		rt.Log(rtt.INFO, "paid fee debt. amount from vesting table: %v, amount from balance: %v, new fee debt: %v", fromVesting, fromBalance, st.FeeDebt)
```suggestion
		rt.Log(rtt.INFO, "paid fee debt, amount from vesting table: %v, amount from balance: %v, new fee debt: %v", fromVesting, fromBalance, st.FeeDebt)
```

2021-11-19 21:13 UTC, arajasek commented on actors/builtin/miner/miner_actor.go
> +		rt.Log(rtt.INFO, "paid fee debt. amount from vesting table: %v, amount from balance: %v, new fee debt: %v", penaltyFromVesting, penaltyFromBalance, st.FeeDebt)
```suggestion
		rt.Log(rtt.INFO, "paid fee debt, amount from vesting table: %v, amount from balance: %v, new fee debt: %v", penaltyFromVesting, penaltyFromBalance, st.FeeDebt)
```

2021-11-19 21:13 UTC, arajasek commented on actors/builtin/miner/miner_actor.go
> +		rt.Log(rtt.INFO, "added penalty to fee debt. about added: %v, new total fee debt: %v", faultPenalty, st.FeeDebt)
```suggestion
		rt.Log(rtt.INFO, "added penalty to fee debt, amount added: %v, new total fee debt: %v", faultPenalty, st.FeeDebt)
```

2021-11-19 21:13 UTC, arajasek commented on actors/builtin/miner/miner_actor.go
> +		rt.Log(rtt.INFO, "paid fee debt. amount from vesting table: %v, amount from balance: %v, new fee debt: %v", penaltyFromVesting, penaltyFromBalance, st.FeeDebt)
```suggestion
		rt.Log(rtt.INFO, "paid fee debt, amount from vesting table: %v, amount from balance: %v, new fee debt: %v", penaltyFromVesting, penaltyFromBalance, st.FeeDebt)
```

2021-11-19 21:13 UTC, arajasek commented on actors/builtin/miner/miner_actor.go
> +		rt.Log(rtt.INFO, "added penalty to fee debt. about added: %v, new total fee debt: %v", params.Penalty, st.FeeDebt)
```suggestion
		rt.Log(rtt.INFO, "added penalty to fee debt, amount added: %v, new total fee debt: %v", params.Penalty, st.FeeDebt)
```

2021-11-19 21:13 UTC, arajasek commented on actors/builtin/miner/miner_actor.go
> +		/// XXX am unsure if this is correct! should i be logging amountUnlocked, or VestingSum from addLockedFunds?? could the return value be a bug? confused about what's going on.
I think the return value is correct -- As a side effect of adding locked funds,  some vested funds could be unlocked. The return is just communicating this update.

I don't think this is worth logging at all.

2021-11-19 21:13 UTC, arajasek commented on actors/builtin/miner/miner_actor.go
> +		rt.Log(rtt.INFO, "unlocked vested funds. amount unlocked: %v, new total locked: %v", newlyVested, st.LockedFunds)
Also not worth logging imo

2021-11-28 20:53 UTC, laudiacay commented on actors/builtin/miner/miner_state.go
> +		return xerrors.Errorf("fee debt is negative: %v", st.FeeDebt)
?

2021-11-28 21:05 UTC, laudiacay commented
Closes #1500

2021-11-29 15:35 UTC, arajasek commented on actors/builtin/miner/miner_actor.go
> +		rt.Log(rtt.DEBUG, "added precommit deposit, amt added: %v, new total: %v", depositToUnlock.Neg(), st.PreCommitDeposits)
this (and the `require` above it) are actually unlocking deposit, not adding any

2021-11-29 15:35 UTC, arajasek commented on actors/builtin/miner/miner_actor.go
> +		rt.Log(rtt.DEBUG, "added initial pledge, amt added: %v, new total: %v", totalInitialPledge.Neg(), st.InitialPledge)
also actually unlocking

2021-11-29 19:03 UTC, arajasek approved these changes

2021-11-29 22:21 UTC, merged